---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: sluetzen-frontend-team-security-policy
  namespace: default
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: SC System and Communications Protection
    policy.open-cluster-management.io/controls: SC-7 Boundary Protection
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: sluetzen-frontend-team-security-context-policy
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: LimitRange
                metadata:
                  name: sluetzen-frontend-team-limits
                  namespace: '{{ hub (index .ManagedClusterLabels "name") hub }}'
                spec:
                  limits:
                  - default:
                      cpu: "500m"
                      memory: "1Gi"
                    defaultRequest:
                      cpu: "100m"
                      memory: "128Mi"
                    type: Container
                  - max:
                      cpu: "2"
                      memory: "4Gi"
                    type: Container
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: sluetzen-frontend-team-network-policy
  namespace: default
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: SC System and Communications Protection
    policy.open-cluster-management.io/controls: SC-7 Boundary Protection
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: sluetzen-frontend-team-network-isolation
        spec:
          remediationAction: enforce
          severity: medium
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: networking.k8s.io/v1
                kind: NetworkPolicy
                metadata:
                  name: sluetzen-frontend-team-isolation
                  namespace: '{{ hub (index .ManagedClusterLabels "name") hub }}'
                spec:
                  podSelector: {}
                  policyTypes:
                  - Ingress
                  - Egress
                  ingress:
                  - from:
                    - namespaceSelector:
                        matchLabels:
                          name: openshift-ingress
                    - namespaceSelector:
                        matchLabels:
                          team: frontend-team
                  egress:
                  - {}
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: sluetzen-frontend-team-policy-placement
  namespace: default
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
    - key: environment
      operator: In
      values: ["shared"]
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: sluetzen-frontend-team-security-policy-binding
  namespace: default
placementRef:
  name: sluetzen-frontend-team-policy-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: sluetzen-frontend-team-security-policy
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: sluetzen-frontend-team-network-policy-binding
  namespace: default
placementRef:
  name: sluetzen-frontend-team-policy-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: sluetzen-frontend-team-network-policy
  kind: Policy
  apiGroup: policy.open-cluster-management.io