apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: sluetzen-frontend-team-dev
  labels:
    environment: dev

resources:
- ../../

namespace: sluetzen-frontend-team-dev

commonLabels:
  environment: dev

# Override environment-specific configuration
configMapGenerator:
- name: environment-config
  behavior: replace
  literals:
  - NAMESPACE_NAME=sluetzen-frontend-team-dev
  - ENVIRONMENT=dev
  - CPU_LIMIT=2
  - MEMORY_LIMIT=4Gi
  - STORAGE_LIMIT=10Gi
  - TEAM_NAME=frontend-team
  - CLUSTER_DOMAIN=apps.cluster.local

patchesStrategicMerge:
- namespace-patch.yaml
- resourcequota-patch.yaml

# Environment-specific replacements
replacements:
- source:
    kind: ConfigMap
    name: environment-config
    fieldPath: data.ENVIRONMENT
  targets:
  - select:
      kind: Namespace
    fieldPaths:
    - metadata.labels.environment
    - metadata.annotations.environment
  - select:
      kind: ResourceQuota
    fieldPaths:
    - metadata.labels.environment
  - select:
      kind: Role
    fieldPaths:
    - metadata.labels.environment
  - select:
      kind: RoleBinding
    fieldPaths:
    - metadata.labels.environment
  - select:
      kind: LimitRange
    fieldPaths:
    - metadata.labels.environment