apiVersion: v1
kind: Namespace
metadata:
  name: sluetzen-frontend-team-prod
  labels:
    environment: prod
  annotations:
    environment: prod
    openshift.io/description: "Namespace for frontend-team production environment"
    openshift.io/display-name: "Frontend Team Production"