apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  labels:
    environment: qa
  name: sluetzen-frontend-team-qa

resources:
- ../../base

namespace: sluetzen-frontend-team-qa


# Override environment-specific configuration
configMapGenerator:
- behavior: replace
  literals:
  - NAMESPACE_NAME=sluetzen-frontend-team-qa
  - ENVIRONMENT=qa
  - CPU_LIMIT=4
  - MEMORY_LIMIT=8Gi
  - STORAGE_LIMIT=20Gi
  - TEAM_NAME=frontend-team
  - CLUSTER_DOMAIN=apps.cluster.local
  name: environment-config


# Environment-specific replacements
replacements:
- source:
    fieldPath: data.ENVIRONMENT
    kind: ConfigMap
    name: environment-config
  targets:
  - fieldPaths:
    - metadata.labels.environment
    - metadata.annotations.environment
    select:
      kind: Namespace
  - fieldPaths:
    - metadata.labels.environment
    select:
      kind: ResourceQuota
  - fieldPaths:
    - metadata.labels.environment
    select:
      kind: Role
  - fieldPaths:
    - metadata.labels.environment
    select:
      kind: RoleBinding
  - fieldPaths:
    - metadata.labels.environment
    select:
      kind: LimitRange
labels:
- includeSelectors: true
  pairs:
    environment: qa
patches:
- path: namespace-patch.yaml
- path: resourcequota-patch.yaml
