apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-portal
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: web-portal
        env:
        - name: APP_NAME
          value: "Web Portal (Development)"
        - name: ENVIRONMENT
          value: "development"
        - name: DEBUG_MODE
          value: "true"
        - name: LOG_LEVEL
          value: "DEBUG"
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5