apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: frontend-team-prod-cluster
  labels:
    environment: prod
    cluster: production-cluster

resources:
- ../../

namespace: frontend-team

commonLabels:
  environment: prod
  cluster: production-cluster

# Production cluster specific configuration
configMapGenerator:
- name: cluster-config
  behavior: replace
  literals:
  - CLUSTER_NAME=production-cluster
  - ENVIRONMENT=prod
  - NAMESPACE_NAME=frontend-team
  - CPU_LIMIT=8
  - MEMORY_LIMIT=16Gi
  - STORAGE_LIMIT=50Gi
  - TEAM_NAME=frontend-team
  - CLUSTER_DOMAIN=apps.prod-cluster.local

patchesStrategicMerge:
- namespace-patch.yaml
- resourcequota-patch.yaml