apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: web-portal-cluster-prod
  labels:
    environment: prod
    deployment-type: cluster-based

resources:
- ../../base

namespace: frontend-team

namePrefix: prod-

commonLabels:
  environment: prod
  cluster: production-cluster

patchesStrategicMerge:
- deployment-patch.yaml
- route-patch.yaml
- hpa-patch.yaml

# Environment configuration for cluster-based deployment
configMapGenerator:
- name: web-portal-config
  behavior: merge
  literals:
  - app.properties=|
      app.name=Web Portal (Production Cluster)
      app.environment=prod
      app.version=v1.0.0
      logging.level=WARN
      features.debug=false
- name: environment-config
  literals:
  - ENVIRONMENT=prod
  - NAMESPACE=frontend-team
  - ROUTE_HOST=web-portal.apps.prod-cluster.local
  - CLUSTER_DOMAIN=apps.prod-cluster.local
  - CLUSTER_NAME=production-cluster
  - IMAGE_TAG=v1.0

# Dynamic hostname configuration
replacements:
- source:
    kind: ConfigMap
    name: environment-config
    fieldPath: data.ROUTE_HOST
  targets:
  - select:
      kind: Route
      name: web-portal
    fieldPaths:
    - spec.host

images:
- name: quay.io/redhattraining/hello-world-nginx
  newTag: v1.0

replicas:
- name: web-portal
  count: 3