apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: web-portal-prod
  labels:
    environment: prod

resources:
- ../../base

namespace: frontend-team-prod

namePrefix: prod-

commonLabels:
  environment: prod

patchesStrategicMerge:
- deployment-patch.yaml
- route-patch.yaml
- hpa-patch.yaml

# Environment configuration
configMapGenerator:
- name: web-portal-config
  behavior: merge
  literals:
  - app.properties=|
      app.name=Web Portal (Production)
      app.environment=production
      app.version=v1.0.0
      logging.level=WARN
      features.debug=false
- name: environment-config
  literals:
  - ENVIRONMENT=prod
  - NAMESPACE=frontend-team-prod
  - ROUTE_HOST=web-portal.apps.cluster.local
  - CLUSTER_DOMAIN=apps.cluster.local
  - IMAGE_TAG=v1.0

# Dynamic hostname configuration
replacements:
- source:
    kind: ConfigMap
    name: environment-config
    fieldPath: data.ROUTE_HOST
  targets:
  - select:
      kind: Route
      name: web-portal
    fieldPaths:
    - spec.host

images:
- name: quay.io/redhattraining/hello-world-nginx
  newTag: v1.0

replicas:
- name: web-portal
  count: 3