apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  labels:
    app.kubernetes.io/name: sluetzen-frontend-team-setup
    app.kubernetes.io/part-of: platform-governance
  name: sluetzen-frontend-team-base

resources:
- namespace.yaml
- resourcequota.yaml
- rbac.yaml
- limitrange.yaml

# Default configuration - can be overridden by environment overlays
namespace: sluetzen-frontend-team-dev


# Configuration variables that can be replaced
replacements:
- source:
    fieldPath: data.NAMESPACE_NAME
    kind: ConfigMap
    name: environment-config
  targets:
  - fieldPaths:
    - metadata.name
    select:
      kind: Namespace
  - fieldPaths:
    - metadata.labels.name
    select:
      kind: Namespace
  - fieldPaths:
    - metadata.namespace
    select:
      kind: ResourceQuota
  - fieldPaths:
    - metadata.namespace
    select:
      kind: Role
  - fieldPaths:
    - metadata.namespace
    select:
      kind: RoleBinding
  - fieldPaths:
    - metadata.namespace
    select:
      kind: LimitRange
  - fieldPaths:
    - subjects.[kind=Group].name
    select:
      kind: RoleBinding
      name: sluetzen-frontend-team-admin-binding
  - fieldPaths:
    - subjects.[kind=ServiceAccount].namespace
    select:
      kind: RoleBinding
      name: sluetzen-frontend-team-image-puller

configMapGenerator:
- literals:
  - NAMESPACE_NAME=sluetzen-frontend-team-dev
  - ENVIRONMENT=dev
  - CPU_LIMIT=2
  - MEMORY_LIMIT=4Gi
  - STORAGE_LIMIT=10Gi
  - TEAM_NAME=frontend-team
  name: environment-config
labels:
- includeSelectors: true
  pairs:
    managed-by: platform-team
    team: frontend-team
